apiVersion: v1
kind: Service
metadata:
  name: acme
  labels:
    app: acme
spec:
  selector:
    app: acme
  ports:
  - name: http-svc-port
    port: 8080
    targetPort: http-port
    nodePort: 30080
  type: NodePort
